#!/usr/bin/env python3
"""Generate docs/EVIDENCE.md from what the seed run actually recorded.

WRITTEN RATHER THAN HAND-COPIED, and that is the point. An evidence document
whose numbers were typed in by a person is an evidence document that keeps
looking healthy after the contract stops agreeing with it. This reads
`docs/seed-evidence.json` — which `seed.mjs` wrote from values it read BACK off
the chain — and renders it. If the run did not happen, this produces nothing.

    python3 tools/evidence.py
"""
from __future__ import annotations

import io
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "docs" / "seed-evidence.json"
OUT = ROOT / "docs" / "EVIDENCE.md"


def _as_round_number(key: str) -> int:
    digits = "".join(ch for ch in str(key) if ch.isdigit())
    return int(digits) if digits else 0


def gen(wei) -> str:
    n = int(str(wei or "0"))
    whole, frac = divmod(n, 10 ** 18)
    return f"{whole}.{str(frac).zfill(18)[:4]}"


def main() -> int:
    if not SRC.exists():
        print(f"no {SRC.relative_to(ROOT)} — run `node test/seed.mjs` first")
        return 1
    ev = json.loads(SRC.read_text(encoding="utf8"))
    checks = ev.get("checks", [])
    passed = [c for c in checks if c["ok"]]
    failed = [c for c in checks if not c["ok"]]
    stats = ev.get("stats", {})
    dep = ev.get("deployments", {})
    demo = ev.get("demo", {})

    lines: list[str] = []
    w = lines.append

    w("# EVIDENCE — what actually happened on chain")
    w("")
    w("Generated by `tools/evidence.py` from `docs/seed-evidence.json`, which")
    w("`test/seed.mjs` wrote from values it read BACK off the chain after")
    w("writing them. Nothing in this file was typed in by hand.")
    w("")
    w(f"- **Run started** `{ev.get('started_at', '?')}`")
    w(f"- **Finished** `{ev.get('finished_at', '?')}` "
      f"({ev.get('seconds', 0) / 60:.1f} minutes)")
    w(f"- **Checks** {len(passed)}/{len(checks)} passed")
    w(f"- **Network** GenLayer Studio Devnet, chain "
      f"{dep.get('chain_id', 61997)}")
    w("")

    w("## Contracts")
    w("")
    w("| contract | address | notes |")
    w("|---|---|---|")
    for name in ("GrantJudge", "GrantJudgeDemo", "GrantConsumer"):
        row = dep.get(name)
        if not row:
            continue
        if name == "GrantConsumer":
            note = (f"custody `{str(row.get('custody')).lower()}`, "
                    f"{row.get('payable_methods')} payable methods, reads "
                    f"`{row.get('judge', '')[:10]}…`")
        else:
            note = (f"appeal {row.get('contest_window_s')}s · stall "
                    f"{row.get('stall_ttl_s')}s · cooldown "
                    f"{row.get('round_cooldown_s')}s · rubric "
                    f"{row.get('rubric_version')}")
        w(f"| `{name}` | `{row.get('address')}` | {note} |")
    w("")

    rounds = ev.get("rounds", [])
    if rounds:
        w("## Rounds")
        w("")
        w("| # | name | outcome | pool | awarded | funded | qualified | "
          "rejected | skipped | appeals | locked |")
        w("|---|---|---|---|---|---|---|---|---|---|---|")
        for r in rounds:
            w(f"| {r.get('round_id')} | {r.get('name', '')} | "
              f"**{r.get('outcome', '')}** | {r.get('pool_gen', '—')} | "
              f"{r.get('allocated_gen', '—')} | {r.get('funded', '—')} | "
              f"{r.get('qualified', '—')} | {r.get('rejected', '—')} | "
              f"{r.get('skipped', '—')} | {r.get('contested', '—')} | "
              f"`{r.get('locked_wei', '—')}` |")
        w("")
        drained = [r for r in rounds
                   if str(r.get("locked_wei")) == "0"
                   and r.get("outcome") in ("RANKED", "FINALIZED")]
        if drained:
            w(f"**{len(drained)} round(s) drained to exactly zero wei** once "
              "every claim had landed. That is rule 7 asserted per round rather")
            w("than in aggregate — an aggregate-only invariant is satisfiable by")
            w("a contract that has quietly moved one round's pool into another's.")
            w("")

    # Iterate whatever the collector found rather than a fixed list of names:
    # the rounds are keyed by their real ids, and a run that produced four
    # ranked rounds should not be described by a document that knows about
    # three.
    for key, table in sorted((demo.get("rankings") or {}).items(),
                             key=lambda kv: _as_round_number(kv[0])):
        if not table or not table.get("rows"):
            continue
        w(f"### Round {_as_round_number(key)} — the ranking as the contract computed it")
        w("")
        w("| rank | proposal | author | status | score | requested | awarded | "
          "appeal |")
        w("|---|---|---|---|---|---|---|---|")
        for row in table["rows"]:
            w(f"| {row['rank']} | #{row['proposal_id']} | "
              f"`{row['author'][:10]}…` | {row['status']} | "
              f"{row['score_text']} | {gen(row['requested_wei'])} | "
              f"**{gen(row['award_wei'])}** | {row.get('contest_status') or '—'} |")
        w("")
        if table.get("skipped"):
            w(f"Skipped: {', '.join('#' + str(p) for p in table['skipped'])} — "
              "the network could not score them and a stranger settled them, "
              "returning each deposit in full.")
            w("")

    if stats:
        w("## The books, read off the chain at the end of the run")
        w("")
        w("```")
        w(f"rounds              {stats.get('rounds')}")
        w(f"proposals           {stats.get('proposals')}")
        w(f"evaluations         {stats.get('evaluations')} "
          f"(attempts {stats.get('evaluation_attempts')}, "
          f"inconclusive {stats.get('inconclusive')})")
        w(f"appeals             {stats.get('contests')} "
          f"({stats.get('contests_won')} won)")
        w(f"funded              {stats.get('funded_proposals')}")
        w(f"qualified, unseated {stats.get('qualified_proposals')}")
        w(f"rejected            {stats.get('rejected_proposals')}")
        w(f"skipped             {stats.get('skipped_proposals')}")
        w(f"refusals            {stats.get('refusals')}")
        w("")
        w(f"balance             {gen(stats.get('balance_wei'))} GEN")
        w(f"  locked            {gen(stats.get('locked_wei'))} GEN")
        w(f"  payable           {gen(stats.get('payable_wei'))} GEN")
        w(f"ledger_balanced     {stats.get('ledger_balanced')}")
        w(f"identity            {stats.get('identity')}")
        w(f"chain balance       {stats.get('chain_balance_wei')}")
        w(f"undelivered_wei     {stats.get('undelivered_wei')}")
        w("```")
        w("")
        w("`undelivered_wei` is the gap between the contract's own accounting and")
        w("its real balance on chain. `_pay` posts its transfer with")
        w("`on=\"finalized\"`, and **Studio Dev queues that message and does not")
        w("execute it** — a property of the network, not of this contract. It is")
        w("reported rather than hidden. On a network that delivers, this is zero.")
        w("")

    consumer = ev.get("consumer")
    if consumer:
        reg = consumer.get("registry", {}) or {}
        w("## Composability")
        w("")
        w(f"`GrantConsumer` at `{consumer.get('address')}` holds "
          f"{reg.get('count', 0)} grant(s) worth "
          f"{gen(reg.get('total_award_wei'))} GEN. It registered what the judge "
          "funded and **reverted** on what the judge would not vouch for.")
        w("")

    canonical = ev.get("canonical")
    if canonical:
        w("## The canonical instance")
        w("")
        w(f"`{canonical.get('address')}` runs the brief exactly — a 24-hour "
          "appeal window, a 48-hour stall window, one round per wallet per hour.")
        w(f"Round {canonical.get('open_round')} is open for proposals; round "
          f"{canonical.get('ranked_round')} has been ranked with its full "
          "24-hour appeal window still running.")
        w("")

    w("## Every check, in the order the run made it")
    w("")
    for c in checks:
        mark = "ok" if c["ok"] else "**FAIL**"
        detail = f" — {c['detail']}" if c.get("detail") else ""
        w(f"- {mark} {c['label']}{detail}")
    w("")

    if failed:
        w("## Failures")
        w("")
        for c in failed:
            w(f"- {c['label']} — {c.get('detail', '')}")
        w("")

    w("---")
    w("")
    w("The raw run log is `docs/seed-run.log`; the machine-readable form is")
    w("`docs/seed-evidence.json`. Re-run it yourself with")
    w("`node test/seed.mjs --canonical`.")
    w("")

    OUT.write_text("\n".join(lines), encoding="utf8")
    print(f"wrote {OUT.relative_to(ROOT)} — {len(passed)}/{len(checks)} checks")
    return 0 if not failed else 1


if __name__ == "__main__":
    sys.exit(main())
