#!/usr/bin/env python3
"""Render docs/WORKED-EXAMPLE.md by running one real proposal through the real
contract code.

Every number below is computed by importing `contracts/GrantJudge.py` and
calling the same functions the chain calls. Nothing is typed in, so the example
cannot drift away from the rubric it claims to explain — and if the ladders
change, this file changes with them.

    python3 tools/worked_example.py
"""
from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "test"))
import test_logic as T  # noqa: E402  (installs the runtime stub, then loads the contract)

C = T.C
OUT = ROOT / "docs" / "WORKED-EXAMPLE.md"

FIXTURES = json.loads((ROOT / "test" / "fixtures" / "proposals.json").read_text())
CRITERIA = [
    ("Technical feasibility",
     "Can this team actually build the thing they describe, and does the plan "
     "show they know how?", 3000),
    ("Team experience", "Has this team shipped comparable work before?", 2500),
    ("Community impact", "Who benefits, how many of them, and how directly?", 2500),
    ("Budget reasonableness",
     "Is the money costed out, and is the cost proportionate to the work?", 2000),
]
THRESHOLD = 400


def facts(key: str, evidence: str = "") -> dict:
    v = FIXTURES[key]
    return {
        "round_id": 1, "proposal_id": 1, "round_name": "Ecosystem Growth",
        "description": v["description"], "timeline": v["timeline"],
        "team": v["team"], "evidence": evidence,
        "requested_wei": int(float(v["requested_gen"]) * 10 ** 18),
        "pool_wei": 5 * 10 ** 18, "threshold": THRESHOLD,
        "criteria_names": [c[0] for c in CRITERIA],
        "criteria_descs": [c[1] for c in CRITERIA],
        "criteria_weights": [c[2] for c in CRITERIA],
    }


def table(key: str, evidence: str = "") -> list[str]:
    f = facts(key, evidence)
    read = C._reading(f)
    sig = read["signals"]
    lines: list[str] = []
    w = lines.append
    w("| signal | count | what the contract counted |")
    w("|---|---|---|")
    w(f"| characters | {sig['chars']} | the whole filing: description, timeline, "
      "team" + (", appeal evidence" if evidence else "") + " |")
    w(f"| figures | {sig['numbers']} | maximal runs of digits |")
    w(f"| dates and milestones | {sig['specific']} | distinct words from "
      f"`SPECIFIC_WORDS` |")
    w(f"| budget language | {sig['budget']} | distinct words from `BUDGET_WORDS` |")
    w(f"| track record | {sig['team']} | distinct words from `TEAM_WORDS` |")
    w(f"| named beneficiaries | {sig['impact']} | distinct words from `IMPACT_WORDS` |")
    w(f"| stated risks | {sig['risk']} | distinct words from `RISK_WORDS` |")
    w(f"| filler | {sig['filler']} | distinct words from `FILLER_WORDS` |")
    w(f"| attempts to instruct the scorer | {sig['injection']} | distinct words "
      f"from `INJECTION_WORDS` |")
    w("")
    w(f"Penalty `min(filler + 2 × injection, 4)` = **{C._penalty(sig)}**. "
      f"Depth = **{read['depth']} / 7**.")
    w("")
    w("| criterion | weight | coverage | bracket the evidence earned |")
    w("|---|---|---|---|")
    for i, (name, _desc, weight) in enumerate(CRITERIA):
        lo, hi = read["brackets"][i]
        room = "pinned" if lo == hi else f"{hi - lo + 1} values"
        w(f"| {name} | {weight // 100}% | {read['coverages'][i]} / 3 | "
          f"**{lo}–{hi}** ({room}) |")
    qlo, qhi = read["quality_bracket"]
    w("")
    w(f"Overall quality bracket **{qlo}–{qhi}**. Completeness is deterministic: "
      f"**{read['completeness']} / 7**. A model is consulted: "
      f"**{'yes' if read['model_called'] else 'no'}**.")
    return lines


def outcome(key: str, evidence: str = "") -> tuple[int, int, list[str]]:
    """The floor and ceiling this filing can reach, and the lines describing it."""
    f = facts(key, evidence)
    read = C._reading(f)
    lows = [lo for lo, hi in read["brackets"]]
    highs = [hi for lo, hi in read["brackets"]]
    qlo, qhi = read["quality_bracket"]
    floor = C._weighted(lows, f["criteria_weights"], qlo, read["completeness"])
    ceiling = C._weighted(highs, f["criteria_weights"], qhi, read["completeness"])
    lines = [
        f"Whatever the validators decide, this filing can only land between "
        f"**{C._score_text(floor)}** and **{C._score_text(ceiling)}** out of 7.00. "
        f"The round's bar is {C._score_text(THRESHOLD)}.",
    ]
    return floor, ceiling, lines


def main() -> int:
    lines: list[str] = []
    w = lines.append

    w("# A worked example")
    w("")
    w("Generated by `tools/worked_example.py`, which imports")
    w("`contracts/GrantJudge.py` and calls the same functions the chain calls.")
    w("Every number here is computed, not typed — so this file cannot drift away")
    w("from the rubric it claims to explain.")
    w("")
    w("The round: **5 GEN**, two seats, a bar of "
      f"**{C._score_text(THRESHOLD)} / 7.00**, and four criteria:")
    w("")
    for name, desc, weight in CRITERIA:
        w(f"- **{name}** ({weight // 100}%) — {desc}")
    w("")
    w("---")
    w("")

    for key, title, blurb in (
        ("indexer", "A strong filing",
         "Figures, a three-milestone plan with dates, a costed budget, a named "
         "track record, named beneficiaries and two stated risks."),
        ("explorer", "A thin filing",
         "Not badly written — just underspecified. No figure, no date, no "
         "costing, no track record, no stated risk, and no filler either."),
        ("moonshot", "A filing made of adjectives",
         "The same absence of evidence, plus the filler words that make it "
         "read like a pitch. The difference matters, and it shows up in the "
         "brackets."),
    ):
        w(f"## {title}")
        w("")
        w(blurb)
        w("")
        lines.extend(table(key))
        w("")
        _, _, notes = outcome(key)
        lines.extend(notes)
        w("")

    w("---")
    w("")
    w("## What an appeal actually changes")
    w("")
    w("The thin filing appeals with the detail it left out: milestones with")
    w("months attached, a budget broken into four lines, a named track record,")
    w("a risk and its mitigation. The proposal is read again with that text")
    w("appended — so the SIGNALS change, and so do the brackets.")
    w("")
    before_floor, before_ceiling, _ = outcome("explorer")
    after_floor, after_ceiling, _ = outcome("explorer", FIXTURES["explorer"]["appeal"])
    w("| | before | after the appeal |")
    w("|---|---|---|")
    f_before = C._reading(facts("explorer"))
    f_after = C._reading(facts("explorer", FIXTURES["explorer"]["appeal"]))
    w(f"| depth | {f_before['depth']} / 7 | **{f_after['depth']} / 7** |")
    w(f"| completeness | {f_before['completeness']} / 7 | "
      f"**{f_after['completeness']} / 7** |")
    w(f"| brackets | `{f_before['bracket_csv']}` | **`{f_after['bracket_csv']}`** |")
    w(f"| best it can reach | {C._score_text(before_ceiling)} | "
      f"**{C._score_text(after_ceiling)}** |")
    w(f"| worst it can reach | {C._score_text(before_floor)} | "
      f"**{C._score_text(after_floor)}** |")
    w("")
    w(f"Before the appeal, the best this filing could reach was "
      f"**{C._score_text(before_ceiling)}** — under the "
      f"{C._score_text(THRESHOLD)} bar even if every validator scored it at the "
      "top of every bracket. After it, the ceiling clears the bar. **The appeal "
      "did not buy a score. It bought the room to be given one.**")
    w("")
    w("And the filing made of adjectives appeals too, with more adjectives:")
    w("")
    m_before_floor, m_before_ceiling, _ = outcome("moonshot")
    m_after_floor, m_after_ceiling, _ = outcome("moonshot", FIXTURES["moonshot"]["appeal"])
    m_before = C._reading(facts("moonshot"))
    m_after = C._reading(facts("moonshot", FIXTURES["moonshot"]["appeal"]))
    w("| | before | after the appeal |")
    w("|---|---|---|")
    w(f"| depth | {m_before['depth']} / 7 | **{m_after['depth']} / 7** |")
    w(f"| brackets | `{m_before['bracket_csv']}` | **`{m_after['bracket_csv']}`** |")
    w(f"| best it can reach | {C._score_text(m_before_ceiling)} | "
      f"**{C._score_text(m_after_ceiling)}** |")
    w("")
    w("Nothing moved. That is the property that makes it safe to leave the")
    w("appeal path open to everyone who was rejected: the stake is at risk and")
    w("the ceiling is earned the same way it was the first time.")
    w("")
    w("---")
    w("")
    w("## And then it is addition")
    w("")
    w("Suppose the validators agree on `4,6,6,6` with quality 7 for the strong")
    w("filing. The weighted total is not a matter of opinion:")
    w("")
    strong = C._reading(facts("indexer"))
    scores = [4, 6, 6, 6]
    weights = [c[2] for c in CRITERIA]
    base = sum(s * wt for s, wt in zip(scores, weights)) // 100
    q = 7 * 100
    comp = strong["completeness"] * 100
    total = (base * C.CRITERIA_WEIGHT_BPS + q * C.QUALITY_WEIGHT_BPS
             + comp * C.COMPLETENESS_WEIGHT_BPS) // C.BPS
    w("```")
    for s, (name, _d, wt) in zip(scores, CRITERIA):
        w(f"{name:<24} {s} x {wt:>5} bps")
    w(f"{'':<24} {'':>1}   {'-' * 9}")
    w(f"criteria subtotal        {sum(s * wt for s, wt in zip(scores, weights)):>7}"
      f"  // 100 = {base}")
    w(f"quality 7/7                            = {q}")
    w(f"completeness {strong['completeness']}/7 (deterministic)      = {comp}")
    w("")
    w(f"({base} x 8000 + {q} x 1000 + {comp} x 1000) // 10000 = {total}")
    w(f"                                       = {C._score_text(total)} / 7.00")
    w("```")
    w("")
    w(f"Computed here by the contract's own `_weighted`: "
      f"**{C._score_text(C._weighted(scores, weights, 7, strong['completeness']))}**.")
    w("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
